### ISSUE TITLE
No Connect Clusters Found

### ISSUE THREAD

**Issue by conradwt** [confluentinc/cp-all-in-one#109]
**Description**

I'm following the steps from the documentation to add 3 connectors to the Docker Compose **connect service** found [here](https://docs.confluent.io/kafka-connectors/self-managed/extending.html).  Next, it appears to be an issue in connecting to the Kafka Connect Cluster.  When I navigate to the connect clusters, I see the following message:

**No Connect Clusters Found**

Steps

1. cd cp-all-in-one-kraft
2. docker compose up -d

**Troubleshooting**
Identify any existing issues that seem related: https://github.com/confluentinc/cp-all-in-one/issues?q=is%3Aissue

If applicable, please include the output of:
 - `docker-compose logs connect`

```
connect  | 2022-08-30T07:31:18.781689202Z [2022-08-30 07:31:18,781] ERROR Uncaught exception in REST call to /v1/metadata/id (org.apache.kafka.connect.runtime.rest.errors.ConnectExceptionMapper)
connect  | 2022-08-30T07:31:18.781764254Z javax.ws.rs.NotFoundException: HTTP 404 Not Found
connect  | 2022-08-30T07:31:18.781783166Z       at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:252)
connect  | 2022-08-30T07:31:18.781790492Z       at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
connect  | 2022-08-30T07:31:18.781793890Z       at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
connect  | 2022-08-30T07:31:18.781797862Z       at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
connect  | 2022-08-30T07:31:18.781801839Z       at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
connect  | 2022-08-30T07:31:18.781805012Z       at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
connect  | 2022-08-30T07:31:18.781808209Z       at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
connect  | 2022-08-30T07:31:18.781811355Z       at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:234)
connect  | 2022-08-30T07:31:18.781814517Z       at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680)
connect  | 2022-08-30T07:31:18.781817695Z       at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394)
connect  | 2022-08-30T07:31:18.781820796Z       at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)
connect  | 2022-08-30T07:31:18.781823874Z       at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:366)
connect  | 2022-08-30T07:31:18.781829775Z       at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:319)
connect  | 2022-08-30T07:31:18.781846887Z       at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)
connect  | 2022-08-30T07:31:18.781850901Z       at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799)
connect  | 2022-08-30T07:31:18.781854014Z       at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:550)
connect  | 2022-08-30T07:31:18.781857015Z       at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
connect  | 2022-08-30T07:31:18.781860137Z       at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624)
connect  | 2022-08-30T07:31:18.781863256Z       at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
connect  | 2022-08-30T07:31:18.781866258Z       at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1434)
connect  | 2022-08-30T07:31:18.781869364Z       at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
connect  | 2022-08-30T07:31:18.781872414Z       at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
connect  | 2022-08-30T07:31:18.781875429Z       at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594)
connect  | 2022-08-30T07:31:18.781880331Z       at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
connect  | 2022-08-30T07:31:18.781883467Z       at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1349)
connect  | 2022-08-30T07:31:18.781886595Z       at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
connect  | 2022-08-30T07:31:18.781889596Z       at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:234)
connect  | 2022-08-30T07:31:18.781892659Z       at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:179)
connect  | 2022-08-30T07:31:18.781895687Z       at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
connect  | 2022-08-30T07:31:18.781898808Z       at org.eclipse.jetty.server.Server.handle(Server.java:516)
connect  | 2022-08-30T07:31:18.781901881Z       at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:400)
connect  | 2022-08-30T07:31:18.781904957Z       at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:645)
connect  | 2022-08-30T07:31:18.781907939Z       at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:392)
connect  | 2022-08-30T07:31:18.781911006Z       at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
connect  | 2022-08-30T07:31:18.781913982Z       at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
connect  | 2022-08-30T07:31:18.781917005Z       at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
connect  | 2022-08-30T07:31:18.781919984Z       at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
connect  | 2022-08-30T07:31:18.781922989Z       at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
connect  | 2022-08-30T07:31:18.781925979Z       at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
connect  | 2022-08-30T07:31:18.781932984Z       at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
connect  | 2022-08-30T07:31:18.781936289Z       at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
connect  | 2022-08-30T07:31:18.781939370Z       at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409)
connect  | 2022-08-30T07:31:18.781942419Z       at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
connect  | 2022-08-30T07:31:18.781945433Z       at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
connect  | 2022-08-30T07:31:18.781948548Z       at java.base/java.lang.Thread.run(Thread.java:829)
connect  | 2022-08-30T07:31:35.574316438Z [2022-08-30 07:31:35,573] ERROR Uncaught exception in REST call to /v1/metadata/id (org.apache.kafka.connect.runtime.rest.errors.ConnectExceptionMapper)
connect  | 2022-08-30T07:31:35.574407775Z javax.ws.rs.NotFoundException: HTTP 404 Not Found
connect  | 2022-08-30T07:31:35.574434023Z       at org.glassfish.jersey.server.ServerRuntime$1.run(ServerRuntime.java:252)
connect  | 2022-08-30T07:31:35.574442641Z       at org.glassfish.jersey.internal.Errors$1.call(Errors.java:248)
connect  | 2022-08-30T07:31:35.574448324Z       at org.glassfish.jersey.internal.Errors$1.call(Errors.java:244)
connect  | 2022-08-30T07:31:35.574452415Z       at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
connect  | 2022-08-30T07:31:35.574456533Z       at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
connect  | 2022-08-30T07:31:35.574460631Z       at org.glassfish.jersey.internal.Errors.process(Errors.java:244)
connect  | 2022-08-30T07:31:35.574464777Z       at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:265)
connect  | 2022-08-30T07:31:35.574468897Z       at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:234)
connect  | 2022-08-30T07:31:35.574472961Z       at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:680)
connect  | 2022-08-30T07:31:35.574477136Z       at org.glassfish.jersey.servlet.WebComponent.serviceImpl(WebComponent.java:394)
connect  | 2022-08-30T07:31:35.574481224Z       at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:346)
connect  | 2022-08-30T07:31:35.574485550Z       at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:366)
connect  | 2022-08-30T07:31:35.574489761Z       at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:319)
connect  | 2022-08-30T07:31:35.574493844Z       at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:205)
connect  | 2022-08-30T07:31:35.574497898Z       at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:799)
connect  | 2022-08-30T07:31:35.574501957Z       at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:550)
connect  | 2022-08-30T07:31:35.574506009Z       at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
connect  | 2022-08-30T07:31:35.574510163Z       at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:1624)
connect  | 2022-08-30T07:31:35.574527870Z       at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
connect  | 2022-08-30T07:31:35.574532953Z       at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1434)
connect  | 2022-08-30T07:31:35.574537022Z       at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
connect  | 2022-08-30T07:31:35.574541089Z       at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:501)
connect  | 2022-08-30T07:31:35.574545104Z       at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:1594)
connect  | 2022-08-30T07:31:35.574550736Z       at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
connect  | 2022-08-30T07:31:35.574555220Z       at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1349)
connect  | 2022-08-30T07:31:35.574559400Z       at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
connect  | 2022-08-30T07:31:35.574563537Z       at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:234)
connect  | 2022-08-30T07:31:35.574567722Z       at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:179)
connect  | 2022-08-30T07:31:35.574571736Z       at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
connect  | 2022-08-30T07:31:35.574575766Z       at org.eclipse.jetty.server.Server.handle(Server.java:516)
connect  | 2022-08-30T07:31:35.574579763Z       at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:400)
connect  | 2022-08-30T07:31:35.574583790Z       at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:645)
connect  | 2022-08-30T07:31:35.574587807Z       at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:392)
connect  | 2022-08-30T07:31:35.574591908Z       at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:277)
connect  | 2022-08-30T07:31:35.574595900Z       at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
connect  | 2022-08-30T07:31:35.574599999Z       at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:105)
connect  | 2022-08-30T07:31:35.574604091Z       at org.eclipse.jetty.io.ChannelEndPoint$1.run(ChannelEndPoint.java:104)
connect  | 2022-08-30T07:31:35.574608184Z       at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:338)
connect  | 2022-08-30T07:31:35.574612219Z       at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:315)
connect  | 2022-08-30T07:31:35.574616262Z       at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:173)
connect  | 2022-08-30T07:31:35.574620309Z       at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
connect  | 2022-08-30T07:31:35.574624461Z       at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:409)
connect  | 2022-08-30T07:31:35.574628520Z       at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:883)
connect  | 2022-08-30T07:31:35.574632575Z       at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:1034)
connect  | 2022-08-30T07:31:35.574641104Z       at java.base/java.lang.Thread.run(Thread.java:829)
```

 - any other relevant commands

Dockerfile:

```dockerfile
FROM confluentinc/cp-kafka-connect-base

RUN confluent-hub install --no-prompt jcustenborder/kafka-connect-twitter:0.3.34 && \
  confluent-hub install --no-prompt confluentinc/kafka-connect-jdbc:10.5.2 && \
  confluent-hub install --no-prompt confluentinc/kafka-connect-elasticsearch:14.0.0
```

```docker-compose
---
# version: '2'
services:
  broker:
    image: confluentinc/cp-kafka:7.2.1
    hostname: broker
    container_name: broker
    ports:
      - '9092:9092'
      - '9101:9101'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@broker:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://broker:29092,CONTROLLER://broker:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
    volumes:
      - ./update_run.sh:/tmp/update_run.sh
    command: 'bash -c ''if [ ! -f /tmp/update_run.sh ]; then echo "ERROR: Did you forget the update_run.sh file that came with this docker-compose.yml file?" && exit 1 ; else /tmp/update_run.sh && /etc/confluent/docker/run ; fi'''

  schema-registry:
    image: confluentinc/cp-schema-registry:7.2.1
    hostname: schema-registry
    container_name: schema-registry
    depends_on:
      - broker
    ports:
      - '8081:8081'
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'broker:29092'
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081

  connect:
    # the default image appears to be AMD64 and not arm64
    # image: cnfldemos/cp-server-connect-datagen:0.5.3-7.2.1
    image: conradwt/kafka-connectors:1.0.0
    hostname: connect
    container_name: connect
    depends_on:
      - broker
      - schema-registry
    ports:
      - '8083:8083'
    environment:
      CONNECT_BOOTSTRAP_SERVERS: 'broker:29092'
      CONNECT_REST_ADVERTISED_HOST_NAME: connect
      CONNECT_GROUP_ID: compose-connect-group
      CONNECT_CONFIG_STORAGE_TOPIC: docker-connect-configs
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_OFFSET_FLUSH_INTERVAL_MS: 10000
      CONNECT_OFFSET_STORAGE_TOPIC: docker-connect-offsets
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_STATUS_STORAGE_TOPIC: docker-connect-status
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: 1
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.storage.StringConverter
      CONNECT_VALUE_CONVERTER: io.confluent.connect.avro.AvroConverter
      CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL: http://schema-registry:8081
      # CLASSPATH required due to CC-2422
      CLASSPATH: /usr/share/java/monitoring-interceptors/monitoring-interceptors-7.2.1.jar
      CONNECT_PRODUCER_INTERCEPTOR_CLASSES: 'io.confluent.monitoring.clients.interceptor.MonitoringProducerInterceptor'
      CONNECT_CONSUMER_INTERCEPTOR_CLASSES: 'io.confluent.monitoring.clients.interceptor.MonitoringConsumerInterceptor'
      CONNECT_PLUGIN_PATH: '/usr/share/java,/usr/share/confluent-hub-components'
      CONNECT_LOG4J_LOGGERS: org.apache.zookeeper=ERROR,org.I0Itec.zkclient=ERROR,org.reflections=ERROR

  control-center:
    image: confluentinc/cp-enterprise-control-center:7.2.1
    hostname: control-center
    container_name: control-center
    depends_on:
      - broker
      - schema-registry
      - connect
      - ksqldb-server
    ports:
      - '9021:9021'
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: 'broker:29092'
      CONTROL_CENTER_CONNECT_CONNECT-DEFAULT_CLUSTER: 'connect:8083'
      CONTROL_CENTER_KSQL_KSQLDB1_URL: 'http://ksqldb-server:8088'
      CONTROL_CENTER_KSQL_KSQLDB1_ADVERTISED_URL: 'http://localhost:8088'
      CONTROL_CENTER_SCHEMA_REGISTRY_URL: 'http://schema-registry:8081'
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
      CONFLUENT_METRICS_TOPIC_REPLICATION: 1
      PORT: 9021

  ksqldb-server:
    image: confluentinc/cp-ksqldb-server:7.2.1
    hostname: ksqldb-server
    container_name: ksqldb-server
    depends_on:
      - broker
      - connect
    ports:
      - '8088:8088'
    environment:
      KSQL_CONFIG_DIR: '/etc/ksql'
      KSQL_BOOTSTRAP_SERVERS: 'broker:29092'
      KSQL_HOST_NAME: ksqldb-server
      KSQL_LISTENERS: 'http://0.0.0.0:8088'
      KSQL_CACHE_MAX_BYTES_BUFFERING: 0
      KSQL_KSQL_SCHEMA_REGISTRY_URL: 'http://schema-registry:8081'
      KSQL_PRODUCER_INTERCEPTOR_CLASSES: 'io.confluent.monitoring.clients.interceptor.MonitoringProducerInterceptor'
      KSQL_CONSUMER_INTERCEPTOR_CLASSES: 'io.confluent.monitoring.clients.interceptor.MonitoringConsumerInterceptor'
      KSQL_KSQL_CONNECT_URL: 'http://connect:8083'
      KSQL_KSQL_LOGGING_PROCESSING_TOPIC_REPLICATION_FACTOR: 1
      KSQL_KSQL_LOGGING_PROCESSING_TOPIC_AUTO_CREATE: 'true'
      KSQL_KSQL_LOGGING_PROCESSING_STREAM_AUTO_CREATE: 'true'

  ksqldb-cli:
    image: confluentinc/cp-ksqldb-cli:7.2.1
    container_name: ksqldb-cli
    depends_on:
      - broker
      - connect
      - ksqldb-server
    entrypoint: /bin/sh
    tty: true

  ksql-datagen:
    image: confluentinc/ksqldb-examples:7.2.1
    hostname: ksql-datagen
    container_name: ksql-datagen
    depends_on:
      - ksqldb-server
      - broker
      - schema-registry
      - connect
    command: "bash -c 'echo Waiting for Kafka to be ready... && \
      cub kafka-ready -b broker:29092 1 40 && \
      echo Waiting for Confluent Schema Registry to be ready... && \
      cub sr-ready schema-registry 8081 40 && \
      echo Waiting a few seconds for topic creation to finish... && \
      sleep 11 && \
      tail -f /dev/null'"
    environment:
      KSQL_CONFIG_DIR: '/etc/ksql'
      STREAMS_BOOTSTRAP_SERVERS: broker:29092
      STREAMS_SCHEMA_REGISTRY_HOST: schema-registry
      STREAMS_SCHEMA_REGISTRY_PORT: 8081

  rest-proxy:
    image: confluentinc/cp-kafka-rest:7.2.1
    depends_on:
      - broker
      - schema-registry
    ports:
      - 8082:8082
    hostname: rest-proxy
    container_name: rest-proxy
    environment:
      KAFKA_REST_HOST_NAME: rest-proxy
      KAFKA_REST_BOOTSTRAP_SERVERS: 'broker:29092'
      KAFKA_REST_LISTENERS: 'http://0.0.0.0:8082'
      KAFKA_REST_SCHEMA_REGISTRY_URL: 'http://schema-registry:8081'

  #
  # customizations
  #

  # we will use elasticsearch as one of our sinks.
  # This configuration allows you to start elasticsearch
  elasticsearch:
    image: itzg/elasticsearch:2.4.3
    environment:
      PLUGINS: appbaseio/dejavu
      OPTS: -Dindex.number_of_shards=1 -Dindex.number_of_replicas=0
    ports:
      - '9200:9200'

  # we will use postgres as one of our sinks.
  # This configuration allows you to start postgres
  postgres:
    image: postgres:9.5-alpine
    environment:
      POSTGRES_USER: postgres # define credentials
      POSTGRES_PASSWORD: postgres # define credentials
      POSTGRES_DB: postgres # define database
    ports:
      - 5432:5432 # Postgres port
```

**Environment**
 - GitHub branch: [e.g. `6.0.1-post`, etc] 7.2.1-post (cp-all-in-one/cp-all-in-one-kraft)
 - Operating System: macOS 12.5.1
 - Version of Docker:  20.10.17
 - Version of Docker Compose:   Docker Compose version v2.7.0
 - Docker Desktop Resources:  8 GB RAM, 4 CPUs, 1 GB Swap, and 59.6 GB Storage

**Hardware**

- Apple M1 Max MacBook Pro
- 64 GB RAM
- 4 TB SSD

**Comment by OneCricketeer** [comment]
Duplicate? https://github.com/confluentinc/cp-all-in-one/issues/94#issuecomment-1236187420
