### ISSUE TITLE
Connection to node 0 (localhost/127.0.0.1:9092) could not be established. Broker may not be available

### ISSUE THREAD

**Issue by navkumar2245** [confluentinc/cp-all-in-one#12]
steps to replicate:

1)  git clone https://github.com/confluentinc/cp-all-in-one.git ( branch 5.5.0-post)
2) cd cp-all-in-one && docker-compose up -d
3) confluent-hub install debezium/debezium-connector-mysql:latest ( inside connect docker container)
4) curl -i -X POST -H "Accept:application/json" \
    -H  "Content-Type:application/json" http://localhost:8083/connectors/ \
    -d '{
      "name": "inventory-connector",
      "config": {
            "connector.class": "io.debezium.connector.mysql.MySqlConnector",
            "database.hostname": "mysq",
            "database.port": "3306",
            "database.user": "dbmaster",
            "database.password": "password",
            "database.server.id": "1",
            "database.server.name": "stage",
             "database.dbname": "test",
            "database.history.kafka.bootstrap.servers": "broker:9092",
             "database.history.kafka.topic": "dbtopic",
             "database.whitelist": "test_client",
            "include.schema.changes": "true"

       }
    }'
response was created successfully
docker logs -f connect 
[Producer clientId=inventory-connector-dbhistory] Connection to node 0 (localhost/127.0.0.1:9092) could not be established. Broker may not be available. (org.apache.kafka.clients.NetworkClient)
INFO [AdminClient clientId=inventory-connector-dbhistory] Metadata update failed (org.apache.kafka.clients.admin.internals.AdminMetadataManager)
org.apache.kafka.common.errors.TimeoutException: Call(callName=fetchMetadata, deadlineMs=1589028250610) timed out at 9223372036854775807 after 1 attempt(s)
Caused by: org.apache.kafka.common.errors.TimeoutException: The AdminClient thread has exited.
[2020-05-09 12:44:09,709] INFO Stopping down connector (io.debezium.connector.common.BaseSourceTask)
[2020-05-09 12:44:09,709] INFO Stopping MySQL connector task (io.debezium.connector.mysql.MySqlConnectorTask)
[2020-05-09 12:44:09,709] INFO WorkerSourceTask{id=inventory-connector-0} Committing offsets (org.apache.kafka.connect.runtime.WorkerSourceTask)
[2020-05-09 12:44:09,710] INFO WorkerSourceTask{id=inventory-connector-0} flushing 0 outstanding messages for offset commit (org.apache.kafka.connect.runtime.WorkerSourceTask)
[2020-05-09 12:44:09,710] ERROR WorkerSourceTask{id=inventory-connector-0} Task threw an uncaught and unrecoverable exception (org.apache.kafka.connect.runtime.WorkerTask)
org.apache.kafka.connect.errors.ConnectException: Creation of database history topic failed, please create the topic manually
	at io.debezium.relational.history.KafkaDatabaseHistory.initializeStorage(KafkaDatabaseHistory.java:365)
	at io.debezium.connector.mysql.MySqlSchema.intializeHistoryStorage(MySqlSchema.java:268)
	at io.debezium.connector.mysql.MySqlTaskContext.initializeHistoryStorage(MySqlTaskContext.java:195)
	at io.debezium.connector.mysql.MySqlConnectorTask.start(MySqlConnectorTask.java:144)
	at io.debezium.connector.common.BaseSourceTask.start(BaseSourceTask.java:104)
	at org.apache.kafka.connect.runtime.WorkerSourceTask.execute(WorkerSourceTask.java:213)
	at org.apache.kafka.connect.runtime.WorkerTask.doRun(WorkerTask.java:184)
	at org.apache.kafka.connect.runtime.WorkerTask.run(WorkerTask.java:234)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by dash7ou** [comment]
@navkumar2245  I have the same issue did u solve it?

**Comment by Jiang-Le** [comment]
@navkumar2245 same to me

**Comment by itabr** [comment]
same

**Comment by navkumar2245** [comment]
set DOCKER_HOST_IP

**Comment by Jiang-Le** [comment]
here is an article describing this issue, [Kafka Listeners - Explained](https://rmoff.net/2018/08/02/kafka-listeners-explained/). it works for me.

**Comment by dcguim** [comment]
Exactly, `listeners` and `advertised.listeners` on config/server.properties, or the respective environment variables, have to be configured.

**Comment by OneCricketeer** [comment]
@navkumar2245 You appear to have fixed your issue. If so, please close this issue

**Comment by trinh-hoang-hiep** [comment]
So, what is the problem here, and how to solve it?
