### ISSUE TITLE
java.lang.NoSuchFieldError: DEFAULT_SOCKET_CONNECTION_SETUP_TIMEOUT_MS

### ISSUE THREAD

**Issue by izzie88** [confluentinc/cp-all-in-one#76]
Kafka connect does not start up. it dies when it throws the error :  java.lang.NoSuchFieldError: **DEFAULT_SOCKET_CONNECTION_SETUP_TIMEOUT_MS**

**Troubleshooting**
Identify any existing issues that seem related: https://github.com/confluentinc/cp-all-in-one/issues?q=is%3Aissue

If applicable, please include the output of:
connect1            | [2021-08-08 00:23:22,041] ERROR Stopping due to error(org.apache.kafka.connect.cli.ConnectDistributed)
connect1            | java.lang.NoSuchFieldError: **DEFAULT_SOCKET_CONNECTION_SETUP_TIMEOUT_MS**
connect1            | 	at org.apache.kafka.connect.runtime.distributed.DistributedConfig.<clinit>(DistributedConfig.java:245)
connect1            | 	at org.apache.kafka.connect.cli.ConnectDistributed.startConnect(ConnectDistributed.java:95)
connect1            | 	at org.apache.kafka.connect.cli.ConnectDistributed.main(ConnectDistributed.java:80)

**Environment**
 - cp-kakfka-connect-6.2.0
 - Operating System: ubuntu
 - Version of Docker: 20.10.7
 - Version of Docker Compose: 1.21.2
 
 Kafka-connect keeps dying after the error above is logged. 
zookeper and broker running fine.

**Comment by OneCricketeer** [comment]
Without seeing your actual run command (the variables you've given to the connect image), this issue seems to be related to Kafka itself, not the image (thus would be posted to Kafka JIRA)

**Comment by gmeena** [comment]
Did you find any solution for this issue?

**Comment by kennyliu123** [comment]
我现在也遇到了同样的问题，请问你是如何解决的。
